---
deployment:
  tasks:
    - export DEPLOYPATH=/home/uy7hij3i/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
      /bin/cp -R js $DEPLOYPATH
